# Generated by Django 2.1.1 on 2019-04-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0003_indexlist_heuregular'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexlist',
            name='Standard',
            field=models.FloatField(default=0),
        ),
    ]
