# Generated by Django 2.1.1 on 2019-04-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0004_indexlist_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexlist',
            name='HigherAdvice',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexlist',
            name='LowerAdvice',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
