# Generated by Django 2.1.1 on 2019-04-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='SearchHistory',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
