# Generated by Django 2.1.1 on 2019-05-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyEva', '0007_userlist_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlist',
            name='isMust',
        ),
        migrations.RemoveField(
            model_name='heuevaresult',
            name='ScreenShot',
        ),
        migrations.RemoveField(
            model_name='questionlist',
            name='isMust',
        ),
    ]
